name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Add PR Comment
      uses: Man-Jain/mesg-pr-action@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        # allow messages to be repeated
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy ur project.
