name: CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Pull Request Review
      uses: Man-Jain/mesg-pr-action@v6
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
