name: ci
on: [push]
env:
  NPM: '6.13.1'
  CI: true
jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        node: ['10.x', 'lts/*', 'node']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Setup Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
        uses: dcodeIO/setup-node-nvm@master
        with:
          node-version: ${{ matrix.node }}
      - name: Use NVM
        uses: dcodeIO/setup-node-nvm@master
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"
      - name: Upgrade NPM
        run: |
          npm i -g npm@$NPM
      - name: Unit test
        run: |
          npm ci
          npm run build
          npm run test